config/routes.rb
Rails.application.routes.draw do

  resources :states do
    resources :counties, except: [:index] do
      resources :localities, except: [:index]
    end
  end

  devise_for :users
  root 'welcome#index'

end

app/models/county.rb
class County < ActiveRecord::Base
  belongs_to :state
  has_many :localities, dependent: :destroy

  def localitied?
    self.localities.present? == true
  end

  def staight(countee)
    State.find_by_id(countee.state_id)
  end

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  belongs_to :county

  def countee(loc)
    County.find_by_id(loc.county_id)
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :counties, dependent: :destroy

  def smart_alpha
    self.name.sub(/^the /i, "").sub(/[()]/, "")
  end

  def self.sorted_by_smart_alpha
    State.all.sort_by(&:smart_alpha)
  end

  def countied?
    self.counties.present? == true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController

  def show
    @state = State.find(params[:state_id])
    @county = County.find(params[:id])
  end

  def new
    @state = State.find(params[:state_id])
    @county = County.new
  end

  def create
    @county = County.new(county_params)
    @state = State.find(params[:state_id])
    @county.state = @state

    if @county.save
      flash[:notice] = 'County was saved successfully.'
      redirect_to [@state, @county]
    else
      flash.now[:alert] = "There was an error saving the county. Please try again."
      render :new
    end
  end

  def edit
    @state = State.find(params[:state_id])
    @county = County.find(params[:id])
  end

  def update
    @state = State.find(params[:state_id])
    @county = County.find(params[:id])
    @county.assign_attributes(county_params)
    @county.state_id = params[:county][:state_id]  

    if @county.save
      flash[:notice] = 'County was updated successfully.'
      redirect_to [@state, @county]
    else
      flash.now[:alert] = "There was an error updating the county. Please try again."
      render :new
    end
  end

  def destroy
    @state = State.find(params[:state_id])
    @county = County.find(params[:id])
 
     if @county.destroy
       flash[:notice] = "\"#{@county.name}\" was deleted successfully."
       redirect_to @county.state
     else
       flash.now[:alert] = "There was an error deleting the county."
       render :show
     end
   end

  private
 
   def county_params
    params.require(:county).permit(:name, :population, :note)
   end

 end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController

  def show
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])
    @locality = Locality.find(params[:id])
  end

  def new
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])
    @locality = Locality.new
  end

  def create
    @locality = Locality.new(locality_params)
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])

    if @locality.save
      flash[:notice] = 'Locality was saved successfully.'
      redirect_to [@state, @county, @locality]
    else
      flash.now[:alert] = "There was an error saving the locality. Please try again."
      render :new
    end
  end

  def edit
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])
    @locality = Locality.find(params[:id])
  end

  def update
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])
    @locality = Locality.find(params[:id])
    @locality.assign_attributes(locality_params)
    @locality.county_id = params[:locality][:county_id]
 
     if @locality.save
       flash[:notice] = "Gobblegorf was updated successfully."
       redirect_to [@state, @county, @locality]
     else
       flash.now[:alert] = "There was an error saving this Gobblegorf. Please try again."
       render :edit
     end
   end

  def edit
    @locality = Locality.find(params[:id])
    @state = State.find(params[:state_id])
    @county = County.find(params[:county_id])
    @locality = Locality.find(params[:id])
  end

  def destroy
  end

  private

   def locality_params
    params.require(:locality).permit(:name, :population, :locality_type, :note)
   end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  
  def index
    @states = State.all
  end

  def show
    @state = State.find(params[:id])
  end

  def new
    @state = State.new
  end

  def create

    @state = State.new(state_params)

    if @state.save
      flash[:notice] = 'State was saved successfully.'
      redirect_to @state
    else
      flash.now[:alert] = "There was an error saving the state. Please try again."
      render :new
    end
  end

  def edit
    @state = State.find(params[:id])
  end

   def update
    @state = State.find(params[:id])
    @state.assign_attributes(state_params)
 
     if @state.save
       flash[:notice] = "State was updated successfully."
       redirect_to @state
     else
       flash.now[:alert] = "There was an error saving this state. Please try again."
       render :edit
     end
   end

  def destroy
    @state = State.find(params[:id])
 
     if @state.destroy
       flash[:notice] = "\"#{@state.name}\" was deleted successfully."
       redirect_to states_path
     else
       flash.now[:alert] = "There was an error deleting the State."
       render :show
     end
   end

   private

   def state_params
    params.require(:state).permit(:name, :population, :x, :y, :note)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper

class HTMLWithoutBlockElements < Redcarpet::Render::HTML

  def initialize(opts = {})
    opts[:tables] = false
      super(opts)
  end

      # Regular markdown, just ignore all the block-level elements

      def block_code(code, language)
        code
      end

      def block_quote(quote)
        quote
      end

      def block_html(raw_html)
        raw_html
      end

      def header(text, header_level)
        "#{text} "
      end

      def hrule
        " "
      end

      def list(contents, list_type)
        " #{contents}"
      end

      def list_item(text, list_type)
        "* #{text}"
      end

      def paragraph(text)
        text
      end

      # Span-level calls

      def linebreak
        " "
      end

      # Postprocessing: strip the newlines

  def postprocess(document)
    document.gsub("\n", ' ').strip
  end

end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {autolink: true, highlight: true, disable_indented_code_blocks: true, space_after_headers: false, underline: true, quote: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

  def markdown_line(markdown)
    redcarpet = Redcarpet::Markdown.new(HTMLWithoutBlockElements, autolink: true, highlight: true, strikethrough: true, fenced_code_blocks: false, underline: true, space_after_headers: true)
    (redcarpet.render markdown).html_safe    
  end

  def ogtitle
    if controller.controller_name == 'shows' && controller.action_name == 'show'
      @show.datinator
    elsif controller.controller_name == 'songs' && controller.action_name == 'show'
      @song.title
    elsif controller.controller_name == 'releases' && controller.action_name == 'show'
      @release.title
    else
      'The Gravel Pit'
    end
  end

  def ogdescription
    if controller.controller_name == 'shows' && controller.action_name == 'show'
      @show.description_and_bill
    elsif controller.controller_name == 'songs' && controller.action_name == 'show'
      @song.song_rating
    elsif controller.controller_name == 'releases' && controller.action_name == 'show'
      @release.release_rating
    else
      'For the discerning fan of The Gravel Pit'
    end
  end

end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/counties/edit.html.erb
<h1>Edit County</h1>
 
<div class="row">
  <div class="col-md-12">
    <%= form_for [@state, @county] do |f| %>
      <div>
        <%= f.label :state %>
        <%= f.collection_select :state_id, State.order(:name),:id,:name, include_blank: false %>
      </div>
      <div>
        <%= f.label :county %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the County" %>
      </div>
      <div class="form-group">
        <%= f.label :population %>
        <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 500 and 30,000", in: 500..30000, step: 'any' %>
      </div>
      <div class="form-group">
        <%= f.label :note %>
        <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
      </div>
 
      <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
 </div>

 <% end %>

app/views/counties/new.html.erb
 <h1>New County</h1>
 
  <div class="row">
    <div class="col-md-12">
      <%= form_for [@state, @county] do |f| %>
        <div>
          <%= f.label "State:" %>
          <%= link_to @state.name, state_path(@state)%>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the county" %>
        </div>
        <div class="form-group">
          <%= f.label :population %>
          <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 500 and 30,000", in: 500..30000, step: 500 %>
        </div>
        <div class="form-group">
          <%= f.label :note %>
          <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
        </div>
 
    <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
</div>

<% end %>

app/views/counties/show.html.erb
<h1><%= @county.name %></h1>
 
<div class="row">
  <div class="col-md-12">
    <p><span class="glyphicon glyphicon-print" aria-hidden="true"></span> State: <%= link_to @county.state.name, @state %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Population: <%= number_with_delimiter(@state.population) %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <% @county.localities.each do |locality| %><p><span class="glyphicon glyphicon-knight" aria-hidden="true"></span> Locality: <%= link_to locality.name, state_county_locality_path(@state, @county, locality) %></p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <p><%= markdown_to_html(@county.note) %></p>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-12">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to "Edit", edit_state_county_path(@state, @county)%>
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <%= link_to "Delete", state_county_path(@state, @county), method: :delete, data: {confirm: 'Are you sure you want to delete this county?'} %>
   </div>  
</div>
<hr>
<div class="row">
    <div class="col-md-12">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  <%= link_to "Create New City or Town", new_state_county_locality_path(@state, @county) %>
    </div>
  </div>

  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sinco Island</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= favicon_link_tag 'favicon.ico' %>
  <link href="assets/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "States", states_path %></li>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

    </div>
</body>
</html>

app/views/localities/edit.html.erb
<h1>Edit Town or City</h1>
 
<div class="row">
  <div class="col-md-12">
    <%= form_for [@state, @county, @locality] do |f| %>
      <div>
        <%= f.label :state %>
        <%= f.collection_select :state_id, State.order(:name),:id,:name, {selected: @state.id}  %>
      </div>
      <div>
        <%= f.label :county %>
        <%= f.collection_select :county_id, County.all,:id,:name, {selected: @county.id} %>
      </div>
      <div class="form-group">
        <%= f.label :locality_type %>
        <%= f.select(:locality_type, options_for_select([["City","City"],["Town","Town"]],@locality.locality_type)) %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the City or Town" %>
      </div>
      <div class="form-group">
        <%= f.label :population %>
        <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 500 and 30,000", in: 500..30000, step: 'any' %>
      </div>
      <div class="form-group">
        <%= f.label :note %>
        <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
      </div>
 
      <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
 </div>

 <% end %>

app/views/localities/new.html.erb
 <h1>New City or Town</h1>

  <div class="row">
    <div class="col-md-12">
      <%= form_for [@state, @county, @locality] do |f| %>
      <div>
        <%= f.label :state %>
        <%= f.collection_select :state_id, State.all,:id,:name, {selected: @state.id} %>
      </div>
      <div>
        <%= f.label :county %>
        <%= f.collection_select :county_id, County.all,:id,:name, {selected: @county.id} %>
      </div>
      <div class="form-group">
        <%= f.label :locality_type %>
        <%= f.select(:locality_type, options_for_select([["City","City"],["Town","Town"]],"City")) %>
      </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the city or town" %>
        </div>
        <div class="form-group">
          <%= f.label :population %>
          <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 500 and 30,000", in: 500..30000, step: 500 %>
        </div>
        <div class="form-group">
          <%= f.label :note %>
          <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
        </div>
 
    <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
</div>

<% end %>

app/views/localities/show.html.erb
<h1><%= @locality.name %></h1>
 
<div class="row">
  <div class="col-md-4">
    <p><span class="glyphicon glyphicon-print" aria-hidden="true"></span> State: <%= link_to @locality.county.state.name, @state %></p>
  </div>
  <div class="col-md-8">
    <p><span class="glyphicon glyphicon-lamp" aria-hidden="true"></span> County: <%= link_to @locality.county.name, [@state, @county] %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Population: <%= number_with_delimiter(@locality.population) %></p>
  </div>
    <div class="col-md-8">
    <p><span class="glyphicon glyphicon-knight" aria-hidden="true"></span> <%= @locality.locality_type %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-12"
    <p><%= markdown_to_html(@locality.note) %></p>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-12">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to "Edit", edit_state_county_locality_path(@state, @county, @locality)%>
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <%= link_to "Delete", state_county_path(@state, @county, @locality), method: :delete, data: {confirm: 'Are you sure you want to delete this town or city?'} %>
   </div>  
</div>

</div>

<br>

app/views/states/edit.html.erb
<h1>Edit State</h1>
 
<div class="row">
  <div class="col-md-12">
    <%= form_for @state do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the State" %>
      </div>
      <div class="form-group">
        <%= f.label :population %>
        <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 500 and 30,000", in: 500..30000, step: 'any' %>
      </div>
      <div class="form-group">
        <%= f.label 'X Coordinate'%>
        <%= f.select(:x, options_for_select(1..10,@state.x))%>
        <%= f.label 'Y Coordinate'%>
        <%= f.select(:y, options_for_select(1..10,@state.y))%>
      </div>
      <div class="form-group">
        <%= f.label :note %>
        <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
      </div>
 
      <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
 </div>

 <% end %>

app/views/states/index.html.erb
<h1>Sinco Island States</h1>

<div class="row">
  <div class="col-md-12">
    <% @states.sorted_by_smart_alpha.each_with_index do |state, index| %>
      <h4 class="media-heading">
        <%= index + 1 %> <%= link_to state.name, state %>
      </h4>
        <% if state.countied? %>
          <% state.counties.each.each_with_index do |county, sindex| %>
            <h5 class="media-heading">
              <%= index + 1 %>.<%= sindex + 1 %> <%= link_to county.name, state_county_path(state, county) %>
            </h5>
            <% if county.localitied? %>
          <% county.localities.each.each_with_index do |locality, tindex| %>
            <h6 class="media-heading">
              <%= index + 1 %>.<%= sindex + 1 %>.<%= tindex + 1 %> <%= link_to locality.name, state_county_locality_path(state, county, locality) %>
            </h6>
          <% end %>
        <% end %>
          <% end %>
        <% end %>
        <br>
      <% end %>
      </div>
    </div>
<hr>
<div class="row">
  <div class="col-md-12">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 
    <%= link_to "Create New State", new_state_path %>
  </div>
</div>

app/views/states/new.html.erb
 <h1>New State</h1>
 
  <div class="row">
    <div class="col-md-12">
      <%= form_for @state do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter the name of the State" %>
        </div>
        <div class="form-group">
          <%= f.label :population %>
          <%= f.number_field :population, class: 'form-control', placeholder: "Choose a number between 5,000 and 1,000,000", in: 5000..1000000, step: 5000 %>
        </div>
        <div class="form-group">
          <%= f.label 'X Coordinate'%>
          <%= f.select :x, options_for_select(1..10), class: 'form-control'%>
          <%= f.label 'Y Coordinate'%>
          <%= f.select :y, options_for_select(1..10), class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :note %>
          <%= f.text_area :note, rows: 5, placeholder: "Leave a note or a comment", class: 'form-control'%>
        </div>
 
    <%= f.submit "Save", class: 'btn btn-success'  %>
  </div>
</div>

<% end %>

app/views/states/show.html.erb
<h1><%= @state.name %></h1>
 
<div class="row">
  <div class="col-md-3">
    <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Population: <%= number_with_delimiter(@state.population) %></p>
  </div> 
  <div class="col-md-9">
    <p><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> Coordinates: <%= @state.x %> - <%= @state.y %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <% @state.counties.each do |county| %><p><span class="glyphicon glyphicon-lamp" aria-hidden="true"></span> County: <%= link_to county.name, state_county_path(@state, county) %></p>
    <% end %>
  </div>
</div>
    <p><%= markdown_to_html(@state.note) %></p>
     <br>
<div class="row">
  <div class="col-md-12">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to "Edit ", edit_state_path(@state)%>
      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <%= link_to "Delete ", @state, method: :delete, data: {confirm: 'Are you sure you want to delete this State?'} %>
    </div>
  </div>

<hr>
<div class="row">
    <div class="col-md-12">
      <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>  <%= link_to "Create New County", new_state_county_path(@state) %>
    </div>
  </div>

  <br>

app/views/welcome/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Sinco Island <small>A wiki about the island created by Chester Parish</small></h1>
</div>